name: Build and Deploy Clinical Assistant

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: 'clinical-chatbot'
  CONTAINER_APP_NAME: 'clinicalapp'
  CONTAINER_REGISTRY: 'clinicalapp.azurecr.io'
  IMAGE_NAME: 'clinicalapp'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLINICALAPP_AZURE_CREDENTIALS }}

      - name: Log in to Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.CLINICALAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.CLINICALAPP_REGISTRY_PASSWORD }}

      - name: Build and push image to registry
        run: |
          docker build --no-cache . -t ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLINICALAPP_AZURE_CREDENTIALS }}

      - name: Deploy to container app
        uses: azure/cli@v1
        with:
          inlineScript: |
            az containerapp update \
              --name ${{ env.CONTAINER_APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --image ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest