jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # 1. Log in to Azure using the Service Principal
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    # 2. Log in to your Azure Container Registry
    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: clinicalapp.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    # 3. Build and push your Docker image
    - name: Build and push image
      run: |
        docker build . -t clinicalapp.azurecr.io/my-app:${{ github.sha }}
        docker push clinicalapp.azurecr.io/my-app:${{ github.sha }}