name: Trigger auto deployment for clinicalbot
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/clinicalbot-AutoDeployTrigger-3090ffb9-8e68-4413-bdcc-c014fe468b2b.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.CLINICALBOT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: clinicalapp.azurecr.io
          registryUsername: ${{ secrets.CLINICALBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLINICALBOT_REGISTRY_PASSWORD }}
          containerAppName: clinicalbot
          resourceGroup: DefaultResourceGroup-null
          imageToBuild: clinicalapp.azurecr.io/clinicalbot:latest
          environmentVariables: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
